### PR TITLE
Update TargetFrameworks to net8.0 for Android and iOS (JailbreakDetector)

### PR DESCRIPTION
**Pull request by agustinbishel**
Updated the TargetFrameworks in the project file from net7.0-android;net7.0-ios to net8.0-android;net8.0-ios to leverage the latest features and improvements in .NET 8. This chang addresses compatibility issues with net8.0.

### CODE REVIEW

**Comment by banditoth** [comment]
Hey, Thanks for updating the target frameworks. I will release a new version today / tomorrow of the packages.

**Review by banditoth — APPROVED** [review]

**Comment by agustinbishel** [comment]
Thank you!! if I can help with anything else just tell me.

**Comment by agustinbishel** [comment]
Hi @banditoth! Do you know when the new version will be released? Thank you very much!

**Comment by banditoth** [comment]
Hey, I've updated the TargetFW on other packages aswell, and I've encountered a problem with the DeviceId package compability. I will release the package you requested tomorrow. 😁

**Comment by banditoth** [comment]
Still can't solve the DeviceId package problems, but I've released the other packages with net8.0 compatibility

**Comment by agustinbishel** [comment]
> Still can't solve the DeviceId package problems, but I've released the other packages with net8.0 compatibility

Thank you for your time. I have conducted some tests with the DeviceId project and have found the solutions
I will open a pull request in the other project.

**Pull request closed without merging**
